### ISSUE TITLE
Windows Defender Alert And Virustotal Virus

### ISSUE THREAD

**Issue by JoachimFlottorp** [Kataiser/tf2-rich-presence#126]
Both self extract and zip triggers windows Defender. 

https://www.virustotal.com/gui/file/3357e0c1df2c203ea427034593c2a0a8c5a84e651ac3e989014af55889776a2c/detection

**Comment by Kataiser** [comment]
It's a known issue that some antivirus software get triggered, specifically by the launcher .exes. I tried to fix it by entirely rewriting them in C++, but they were still "detected" in VirusTotal so I abandoned that. If it makes you feel more comfortable, you can move the .bat files in the "resources" folder up one level and run those instead, they function exactly identically to the .exes but don't trigger antiviruses, plus you can look directly at their source code. For the record, the documentation for the program I use to convert batch files to exes mentions that false positives do sometimes happen for whatever reason.

**Comment by Kataiser** [comment]
If anyone has any ideas on how to fix this, I'm all ears.

**Comment by Kataiser** [comment]
It's also worth noting that literally just a "hello world" script, written in C++ and compiled with GCC, is still detected as malware by some some vendors.
