### ISSUE TITLE
stuck on manu

### ISSUE THREAD

**Issue by barrulik** [Kataiser/tf2-rich-presence#196]
![image](https://user-images.githubusercontent.com/62114976/132913546-f76fb987-9b70-4740-9a3e-f28c9cd2d4aa.png)
im stuck on manu

**Comment by Kataiser** [comment]
So you're in a match but seeing this? That's very odd. Would you mind sending me your game's console.log, as well as the program's current log? While in a match of course.

**Comment by barrulik** [comment]
Whoops, i forgot, i will do it as soon as im home, how do i enable logs?

**Comment by barrulik** [comment]
nvm, i just noticed i forgot to do -condebug in launch settings

**Comment by Kataiser** [comment]
Hm, if you're launching from the "launch TF2" button in the program then you shouldn't need condebug, and if not then you shouldn't have rich presence at all. Well as long as it's working now I guess
