### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Luisinhi010** [Kataiser/tf2-rich-presence#212]
in the latest version (2.1) it's not updating the class I'm using

**Comment by Kataiser** [comment]
Hm okay, I've gotten this report before. Would you mind sending me your log? Go to File -> Open save directory and send the most recent file in the logs folder.

**Comment by Luisinhi010** [comment]
[TF2RP_DESKTOP-AMJF453_Claudio_v2.1_0.log](https://github.com/Kataiser/tf2-rich-presence/files/7469330/TF2RP_DESKTOP-AMJF453_Claudio_v2.1_0.log)

**Comment by Kataiser** [comment]
Seems the class configs are correctly modified, but somehow either the echoes are either not ending up in console.log or they're not being correctly read by the program. Would you mind sending me your console.log as well? File -> Open console.log

**Comment by Luisinhi010** [comment]
I think this is happening because I was using masterconfig, I'm not using it anymore and now it's changing the class

**Comment by Kataiser** [comment]
I use mastercomfig too and haven't ever had that issue, and while I see now that it does have custom class configs, my program should append to them anyway. So idk

**Comment by Luisinhi010** [comment]
I'll see what's happening here, anything I'll let you know
