### ISSUE TITLE
crashes when I try to connect to a server

### ISSUE THREAD

**Issue by tylerwolf99** [Kataiser/tf2-rich-presence#214]
Please include the most recent (or at least most relevant) file in the "logs" folder, which you can get to with Help -> Open logs directory.
[TF2RP_DESKTOP-7C1P48A_Tyler Landis_v2.1_4.log](https://github.com/Kataiser/tf2-rich-presence/files/7479410/TF2RP_DESKTOP-7C1P48A_Tyler.Landis_v2.1_4.log)

**Comment by Kataiser** [comment]
Well there's no crash in this log but I got one from Sentry. This crash is already fixed on my end and will be included in the next release, but for now you can just use [this autobuild](https://github.com/Kataiser/tf2-rich-presence/suites/4101112933/artifacts/104617421).

**Comment by tylerwolf99** [comment]
ok thx
