### ISSUE TITLE
The application does not load

### ISSUE THREAD

**Issue by ArmorKeik** [Kataiser/tf2-rich-presence#217]
When I want to open the TF2 Rich Presence application, it keeps loading.

When you hover the cursor over the application icon, it appears all black and if you click on it, it does not open.

![TF2 Rich Presence crash](https://user-images.githubusercontent.com/87909542/142478349-3bf7c5cc-8cc6-40f6-8edf-491ad77756d8.png)

This happens to me with both the stable version and the latest development version: eaa2eaa7334dc9275572e3035f8148854871f96f

Opening the application with the administrator permission does not solve anything, in fact an error message appears (the latter I only tested in the latest development version).
![TF2 RIch Presence crash (Admin)](https://user-images.githubusercontent.com/87909542/142478967-a592eb85-7ba6-4bfc-9a3c-5965bf100ca2.png)

**Comment by Kataiser** [comment]
Hm, the error says pythonw.exe doesn't exist, but in the first screenshot, the program actually started which means it does. Someone else had this issue as well (#206), but it seemed to fix itself for them so idk

**Comment by ArmorKeik** [comment]
I read that the person was able to fix it by opening TF2 Rich Presence from somewhere else, but I tried looking for it from the Windows button, and nothing.

![Buscador](https://user-images.githubusercontent.com/87909542/142494603-9c83e9ce-5a8f-449f-a193-e98910763053.png)

It doesn't work from the shortcut either.

![Pantalla inicio](https://user-images.githubusercontent.com/87909542/142494630-47d001e3-ee0b-4c7c-8e69-2d35f592cac2.png)

**Comment by ArmorKeik** [comment]
And as you said, the file **IS on my computer**.
![Captura de pantalla 2021-11-18 175617](https://user-images.githubusercontent.com/87909542/142495737-e5babc05-ba04-4897-808e-15938d6e706a.png)

**Comment by Kataiser** [comment]
I don't even know how to start fixing this

**Comment by ArmorKeik** [comment]
I have a doubt, can the malfunctioning of TF2 Rich Presence be due to the fact that I have the Python program already installed on my computer?

![image](https://user-images.githubusercontent.com/87909542/144719131-6bf3883a-8d1e-420f-8f9a-4494fb8ebc5e.png)

I share the computer, so I didn't install that program, I only know that it deals with computer science but I don't touch it.

**Comment by Kataiser** [comment]
Doubt it, cause this is running integrated Python in isolated mode. Also I did find the issue and mentioned it here: https://github.com/Kataiser/tf2-rich-presence/issues/206#issuecomment-985900028

**Comment by Kataiser** [comment]
While I'm still not sure what's going on with the pythonw.exe not found thing, the freezing issue should be fixed as of https://github.com/Kataiser/tf2-rich-presence/commit/dbab1e686c60d0e8834d019ad6450f0a95f4081c

**Comment by ArmorKeik** [comment]
Hi, I have downloaded and installed the[ latest version](https://nightly.link/Kataiser/tf2-rich-presence/workflows/Tests.CD/master/TF2RichPresence_v2.1.1_setup.exe.zip) available and the error keeps happening, only that it changed a bit by not opening it as administrator.

https://user-images.githubusercontent.com/87909542/146599479-edd9e52a-fd31-4bc6-85d8-b784a27a9f7c.mp4

At first I open it normally from the shortcut, but the application closes quickly (you can see it from the taskbar).

But then I try to open it with admin permissions, and the same error occurs as before.

**Comment by Kataiser** [comment]
I *think* I might know what's happening, the relative file path isn't working for some reason. Attempted to fix in the [latest build](https://github.com/Kataiser/tf2-rich-presence/suites/4696704681/artifacts/128328970).

**Comment by ArmorKeik** [comment]
> I _think_ I might know what's happening, the relative file path isn't working for some reason. Attempted to fix in the [latest build](https://github.com/Kataiser/tf2-rich-presence/suites/4696704681/artifacts/128328970).

It still won't open, the only change I noticed was that now when I open it as administrator it closes the same way as when I open it normally.

https://user-images.githubusercontent.com/87909542/146617518-1736e9bb-ebf8-4c8b-9c46-e1e9dad975ac.mp4

**Comment by Kataiser** [comment]
Oh huh when I run as admin I get the same thing

**Comment by Kataiser** [comment]
Okay [fixed admin startup](https://github.com/Kataiser/tf2-rich-presence/suites/4698088692/artifacts/128412298), which may have fixed the other issue for you as well. If not, I have some stuff I could send you to try to narrow down the problem.

**Comment by ArmorKeik** [comment]
> Okay [fixed admin startup](https://github.com/Kataiser/tf2-rich-presence/suites/4698088692/artifacts/128412298), which may have fixed the other issue for you as well. If not, I have some stuff I could send you to try to narrow down the problem.

I am sorry to tell you that the problem remains the same for me.

**Comment by Kataiser** [comment]
Alright, let's fix this. In `AppData\Local\Programs\TF2 Rich Presence`, replace TF2 Rich Presence.bat with [this](https://github.com/Kataiser/tf2-rich-presence/files/7739688/TF2.Rich.Presence.txt) and resources\launcher.py with [this](https://github.com/Kataiser/tf2-rich-presence/files/7739700/launcher.txt) (fix extensions of course). Neither should function differently, but if you send me the output it should help narrow down the issue

**Comment by Kataiser** [comment]
Also there's a small chance the start menu shortcut is broken so check that too

**Comment by ArmorKeik** [comment]
![unknown](https://user-images.githubusercontent.com/87909542/146653470-71bfa885-fbe5-48a5-88d6-71676ac4105f.png)
![unknown](https://user-images.githubusercontent.com/87909542/146653475-bfdb8230-5b59-47c8-8e71-93374fd8614e.png)


https://user-images.githubusercontent.com/87909542/146653556-7f5808a7-0ad0-4d96-bef3-317f27915330.mp4

On the desktop you can see the two files you asked me to replace.

According to what I understood, I had to change the name of the extension (txt.) to the name of the original file.

TF2.Rich.Presence.txt > TF2.Rich.Presence.bat

launcher.txt > launcher.py

**Comment by ArmorKeik** [comment]
And here I leave a video opening the .bat from the program folder.

https://user-images.githubusercontent.com/87909542/146653835-77d3e351-828e-4cd0-8818-36de13cc5c41.mp4



![image](https://user-images.githubusercontent.com/87909542/146653765-8eb1df33-1186-473f-b869-e3c1bd9b8f70.png)

**Comment by Kataiser** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhh I see what's happening, there's a bit mismatch between tkinter and Python, which is a problem I've fixed before but I really don't know how it's ended up happening for you

**Comment by Kataiser** [comment]
Assuming you haven't modified the embedded python, and also that it's actually the one that launched, this shouldn't be possible I think

**Comment by ArmorKeik** [comment]
I haven't adjusted anything about the program, I just installed it and opened it.

Maybe it will be a setting my brother will have made with Python, I really don't know.

> I have a doubt, can the malfunctioning of TF2 Rich Presence be due to the fact that I have the Python program already installed on my computer? @Kataiser
> 
> ![image](https://user-images.githubusercontent.com/87909542/144719131-6bf3883a-8d1e-420f-8f9a-4494fb8ebc5e.png)
> 
> I share the computer, so I didn't install that program, I only know that it deals with computer science but I don't touch it.

**Comment by Kataiser** [comment]
Yeah ok you have 64-bit python installed, which seems like a likely culprit but my program really shouldn't care about that (in theory?)

**Comment by ArmorKeik** [comment]
**UPDATE:** I re-downloaded the stable version ([v2.1.1](https://github.com/Kataiser/tf2-rich-presence/releases/tag/v2.1.1)), and this time the program worked.

1️⃣ Here is a screenshot of when I opened it from the shortcut.

![1](https://user-images.githubusercontent.com/87909542/147275394-f63b1ece-f17a-44dc-85d1-68201a3ed54b.png)


2️⃣ And here another one in which I am playing in a server (actually I was in the main menu, but it stayed that I was still playing in the server).

![2](https://user-images.githubusercontent.com/87909542/147275409-8bf88c65-78ac-4a78-98e1-3d795370148f.png)


But ignoring the error in the second screenshot, I can now go back to using TF2 Rich Presence as before 😀

Thanks for your attention, the truth is that your project is moving forward with each update you give it, keep it up! 💪

**Comment by Kataiser** [comment]
Yo nice, and thank you!

**Comment by Kataiser** [comment]
And yeah about that gate state bug, idk it's just cursed I guess
