### ISSUE TITLE
RPC GUI fails to display - Shows up black and crashes if ran as admin

### ISSUE THREAD

**Issue by pinhead-tf2** [Kataiser/tf2-rich-presence#237]
When the app is launched it shows that the app exists and is running, working as normal on Discord and TF2, but it fails to display the GUI of the app itself, instead showing as a black window in alt-tab or taskbar, while not appearing at all when tabbed to. When ran as admin it states that a pythonw.exe is missing from resources. If there are further logs to send I would be more than happy to send those, but I do not know where they are, nor if they exist. 

What it looks like in taskbar: 
![image](https://user-images.githubusercontent.com/42384617/159099685-8c5c5f1d-0946-4a9a-93b0-6b46f38ac54f.png)

What occurs if ran as admin: 
![image](https://user-images.githubusercontent.com/42384617/159099437-547c1e98-ccff-45e3-915a-6158a61ee655.png)

**Comment by Kataiser** [comment]
Thanks for the report, [a fix has already been implemented](https://github.com/Kataiser/tf2-rich-presence/commit/6d5cee2f741b8496f91562631b5ff96e8381d2ed) and will be in the next release.

**Comment by Kataiser** [comment]
I should probably get that release out sooner rather than later actually, I've had a problem on my end (can't query Valve game servers) and I wanted to fix that first, but no one else has reported the issue so maybe it's just me.
