### ISSUE TITLE
After changing map program show "in main menu" state despite be on server.

### ISSUE THREAD

**Issue by asolovev99** [Kataiser/tf2-rich-presence#275]
When first time I connect to "Potato's MvM Holographic Harvest server" (for example, 92.38.186.127:27053) or "EL Grapes's Server" (46.174.50.33:27210) program detects what I'm on server. But when map is changed program show what I'm in main menu despite I'm still on server. If I rejoin then problem returns to "first connected to server" step.
[console.log](https://github.com/Kataiser/tf2-rich-presence/files/9984305/console.log)
[TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log](https://github.com/Kataiser/tf2-rich-presence/files/9984330/TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log)

Looks like [line 174 in console_log.py](https://github.com/Kataiser/tf2-rich-presence/blob/d5fdc3e2ddbb58be20f34e03f3f3afed92d3d4ad/TF2%20Rich%20Presence/console_log.py#L174) cauising it.

Example of bug from console.log and TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log:

Connecting to server:
- "Map: mvm_villa_b5c" (Line 102806 of console.log)
- 
- "[Nov 11 02:23:29 +0.0694] DEBUG: console.log parse results: (False, 'mvm_villa_b5c', '', '92.38.186.127:27065', 'Not queued', False)" (Line 14453 of TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log)

Vote to change map is called:
- "mark_2" (Line 103324 from console.log)

Connecting to server after map change:
- "Map: mvm_legerdemain_a6e" (Line 103326 of console.log)
- "SoundEmitter:  removing map sound overrides [5796 to remove, 1979 to restore]" (Line 103332 of console.log)
-
- "[Nov 11 02:26:40 +0.0593] DEBUG: Menus message used: "SoundEmitter:  removing map sound overrides [5796 to remove, 1979 to restore]"" (Line 15299 of TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log)
- "[Nov 11 02:26:40 +0.0000] DEBUG: Game state updated from (Medic on mvm_villa_b5c, gamemode=mvm, hosting=False, queued="Not queued", server=92.38.186.127:27065) to (in menus, queued="Not queued")" (Line 15305 of TF2RP_LAPTOP-JU5GUNO3_199930_v2.1.2_3.log)

**Comment by Kataiser** [comment]
Thanks for the thorough report, I'll see what I can do about it.

**Comment by Kataiser** [comment]
Alright I removed the SoundEmitter based detection, I'm sure I added it when it seemed necessary but removing it doesn't break any tests so it's probably fine right
