### ISSUE TITLE
Batch File opens and closes immediately. 

### ISSUE THREAD

**Issue by Bevoziastic** [Kataiser/tf2-rich-presence#332]
Tried installing the new version of the rich presence, the installation was successful. However when I try to open the program, it closes immediately after a millisecond. I even have Python installed, is there something I am doing wrong or is it a main issue?

I am running on Windows 10.

**Comment by Kataiser** [comment]
Could you send me the most recent file v2.1.5 log in `\AppData\Roaming\TF2 Rich Presence\logs`? Also try modifying the batch file in `AppData\Local\Programs\TF2 Rich Presence`, replacing line 16 with `"resources\python-3.11.3-embed-win32\python.exe" -I -B "resources\launcher.py"`, and posting a screenshot of the result.

**Comment by KeoLightz** [comment]
The logs doesn't seem to appear whenever I reopen it, I did manage to mo

https://github.com/Kataiser/tf2-rich-presence/assets/49461218/fbaef7ab-c13f-4392-b36e-3393e3eb4135

dify line 16 of what you gave me. But now the command prompt opens and closes after a second than a millisecond when I modified line 16.

**Comment by KeoLightz** [comment]
Didn't mean to mark this as closed, my bad.

**Comment by Kataiser** [comment]
What if you just run that line in a terminal? My best guess is it's not finding either python.exe or launcher.py. Also try fully deleting the program and reinstalling.

**Comment by JTzLinux** [comment]
I've had issues too fixed it with deleting the folder: %APPDATA%\TF2 Rich Presence
