### ISSUE TITLE
[feature request] option for "round number" option in top/bottom line

### ISSUE THREAD

**Issue by RalphORama** [Kataiser/tf2-rich-presence#339]
I play a lot of MvM but I believe this would also be applicable to modes like Competitive, etc.

Basically, an option for top line/bottom line that would output "Round X" or, if there's a max # of rounds (i.e. 7 waves in an MvM match), "Round X of Y"

**Comment by Kataiser** [comment]
Not sure if that's possible but I'll look into it

**Comment by Kataiser** [comment]
Doesn't seem possible, sorry
