### ISSUE TITLE
[Request] Custom RPC Images

### ISSUE THREAD

**Issue by goobert** [Kataiser/tf2-rich-presence#400]
I've been mostly happy with the program but I can't say the same about some of the images used, especially the main menu one. I'd like to request some kind of system for users to use images of their choice if that's feasible.

Maybe you could make any image edits made in `C:\Users\USER\AppData\Local\Programs\TF2 Rich Presence\resources\gui_images` reflect on to the actual images on your profile?

Or maybe you could allow the user to select a custom application ID that would contain their custom images?
[(This is how Minecraft's RPC mod does it.)](https://gitlab.com/CDAGaming/CraftPresence/-/wikis/Making-your-own-Client-ID-+-Using-your-own-Images)

I'm sorry if nothing I suggested is possible, I'm not familiar with how this works.

**Comment by Kataiser** [comment]
Not possible, sorry. RPC images are uploaded by me manually and can't be changed by the program.

**Comment by Kataiser** [comment]
Oh wait I missed the minecraft thing, but that would still require to upload all 208 images

**Comment by goobert** [comment]
I see. Thanks for the response.

**Comment by goobert** [comment]
> Oh wait I missed the minecraft thing, but that would still require you to upload all 208 images

Obviously can't speak for everyone, but I personally wouldn't mind doing that as long as the default images are supplied like they are in the minecraft mod.
