### ISSUE TITLE
Cannot extract file.

### ISSUE THREAD

**Issue by OutDark** [Kataiser/tf2-rich-presence#5]
As in the title, I cannot extract the .zip file. Whenever I try, it leaves an error - [Image](https://i.imgur.com/S82hIIl.png). Thanks.

**Comment by Kataiser** [comment]
Hm, no idea what could cause that. Does it happen during zip extraction, or after? Does it also happen when running the ["installer"](https://github.com/Kataiser/tf2-rich-presence/releases/download/v1.5.9/tf2_rich_presence_v1.5.9_installer.exe) (really just a self-extracting .7z)?

**Comment by OutDark** [comment]
Okay, so I kind of fixed the problem. When I also try to run the installer instead of the .zip file, nothing happens. I tried extracting the .zip with winrar and it worked, so I don't know what's the problem here. Thanks.

**Comment by Kataiser** [comment]
Did you follow the instructions? They're kinda necessary for this program to work. I'll paste them here:

1. Right click on Team Fortress 2 in your Steam library
2. Open properties (very bottom)
3. Click "Set launch options..."
4. Add -condebug
5. OK and Close
6. Restart TF2

**Comment by OutDark** [comment]
Yeah, I followed the instructions but no luck.

**Comment by Kataiser** [comment]
Sorry for the silence (I started a college semester today). If you're still having this problem, could you upload your log file here? It should be the only file in /logs.

**Comment by OutDark** [comment]
Alright. And no worries.
[AJMSI_AJ Coffer_v1.5.9_2aa73008.log](https://github.com/Kataiser/tf2-rich-presence/files/2326513/AJMSI_AJ.Coffer_v1.5.9_2aa73008.log)

**Comment by Kataiser** [comment]
Seems like TF2 itself is acting up and not doing the thing it's supposed to do (creating a file in file called "console.log" in "\Team Fortress 2\tf\") when you add -condebug. No idea what I can do about that. It might have something to do with your system, what OS are you on?

**Comment by OutDark** [comment]
Alright, I think I randomly fixed the problem. I entered -condebug again and it worked. Thanks!

**Comment by Kataiser** [comment]
I may have fixed the installation problem you opened this issue with: https://github.com/Kataiser/tf2-rich-presence/commit/d0c6c804fce4a44c910fbe03bd463c2f199a54c2
