### ISSUE TITLE
Errors with libstdc++.dll

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [Kataiser/tf2-rich-presence#68]
Ever since the most recent update (as of 11/29/19), upon executing any executable from within the included files (`Change settings.exe`, `Launch Rich Presence alongside TF2.exe`, `Launch TF2 with Rich Presence.exe`), a blank terminal for the executable pops up and I get an error as shown in the provided screenshot:

![image](https://user-images.githubusercontent.com/47730899/69894964-46a52a80-12ed-11ea-95f0-be44c0b44947.png)

Following the instructions to the error, I redownload both the `.zip` and setup executable to which the same error occurs.

**Comment by Kataiser** [comment]
Yeah I know it's broken, but somehow v1.10.2 didn't get set as a pre-release. Thanks for the report, nobody should have been getting the update notification yet. I recommend rolling back to v1.10.1 for now.

**Comment by PaxiTheAlchemist** [comment]
Thank you for the quick feedback! hopefully this gets fixed soon!
