### ISSUE TITLE
Giving Error at Startup

### ISSUE THREAD

**Issue by KahootVult** [Kataiser/tf2-rich-presence#84]
I extracted the .zip to a folder on my desktop and when I started it, it gave me this text and said it'll restart after 5 seconds:

Traceback (most recent call last):
  File "C:\Users\Teddy\Desktop\Games\Game Folders\TF2 Rich Presence v1.13\\resou
rces\launcher.py", line 60, in launch
    loaded_module.launch()
  File "main.py", line 91, in main.launch
  File "main.py", line 81, in main.launch
  File "main.py", line 128, in main.TF2RichPresense.run
  File "main.py", line 165, in main.TF2RichPresense.loop_body
UnboundLocalError: local variable 'valid_usernames' referenced before assignment

After it restarts, it shows the same thing again.

**Comment by Kataiser** [comment]
Thanks for the report, I'm away right now but I'll get to it as soon as I can. I think I may know of a fix. For now, see if v1.12 works for you.

**Comment by Kataiser** [comment]
Ok, it seems this happens when TF2 is running but Steam isn't. How'd you manage that? I'll see if I can manage a fix in the meantime. (Steam is needed for this program btw)

**Comment by Kataiser** [comment]
Well I fixed the crash... by yelling at you if Steam isn't open instead lol

Try this build: [tf2_rich_presence_v1.13.zip](https://github.com/Kataiser/tf2-rich-presence/files/4333744/tf2_rich_presence_v1.13.zip)

**Comment by KahootVult** [comment]
That's weird then, because I always have steam running when I play TF2. I'll try this build right now though, and let you know if it fixes anything.

**Comment by KahootVult** [comment]
https://imgur.com/a/43a68gw
This is all it says, no errors but not showing anything on discord. I definitely do have steam running, but idk what's going on.

**Comment by Kataiser** [comment]
Hmm. This program detects if Steam is running by looking for exactly "Steam.exe", which seems to work for everyone except you. If it's not too private, could you paste the results of the console command `tasklist /fi "STATUS eq running"` here?

**Comment by KahootVult** [comment]
For some reason it's running now, and I have no idea how it got fixed. I started it up to do the command like you said but, yea, it works. Really weird tho, no idea what fixed it tbh. Sorry for taking up your time! ;-;

**Comment by KahootVult** [comment]
![image](https://user-images.githubusercontent.com/62162656/76910666-05795c00-6885-11ea-90d9-2f58e7802e7e.png)

well you're not gonna believe this, but it's not working again

**Comment by KahootVult** [comment]
where exactly do I paste the command "tasklist /fi "STATUS eq running"? It won't let me type anything in the program's prompt.

**Comment by Kataiser** [comment]
In the Windows command prompt. Also don't worry about taking up my time, fixing problems is what I'm here for and enjoy doing

**Comment by Kataiser** [comment]
Oh and make sure Steam is running while you do it, and heck TF2 and Discord as well, can't hurt. Just make sure TF2 Rich Presence says "Steam isn't running" as you run the command.

**Comment by KahootVult** [comment]
![image](https://user-images.githubusercontent.com/62162656/77013357-4e451980-6946-11ea-8cef-af65b730298d.png)

these are the results

**Comment by KahootVult** [comment]
![image](https://user-images.githubusercontent.com/62162656/77013487-89474d00-6946-11ea-911c-2b0a0b9562cf.png)

I forgot the second quote, here's the results with the quote

**Comment by Kataiser** [comment]
Ah of course steam.exe can be lowercase for no reason lol

**Comment by Kataiser** [comment]
Alright here you are: 
[tf2_rich_presence_v1.13.zip](https://github.com/Kataiser/tf2-rich-presence/files/4352094/tf2_rich_presence_v1.13.zip)

**Comment by KahootVult** [comment]
![image](https://user-images.githubusercontent.com/62162656/77023749-16989a80-6963-11ea-8ce0-29fb0f81a694.png)

I started it up the usual way, tf2 open, discord open, steam open. Here's what happened lol

**Comment by Kataiser** [comment]
Seems it found Steam and then almost immediately lost it. That's a wtf from me

**Comment by Kataiser** [comment]
Could you upload the file in the logs folder here?

**Comment by KahootVult** [comment]
[Teddy-PC_Teddy_v1.13_18339.log](https://github.com/Kataiser/tf2-rich-presence/files/4352380/Teddy-PC_Teddy_v1.13_18339.log)

**Comment by Kataiser** [comment]
Ok it had me stumped for a while but I think I've got it figured out now. Looks like I'd missed another spot where it assumed an uppercase Steam.exe.

[tf2_rich_presence_v1.13.zip](https://github.com/Kataiser/tf2-rich-presence/files/4363660/tf2_rich_presence_v1.13.zip)

**Comment by Kataiser** [comment]
That log file actually helped a lot

**Comment by KahootVult** [comment]
![image](https://user-images.githubusercontent.com/62162656/77257341-070e9f80-6c4a-11ea-9a6b-e22744145f03.png)
That did the trick for sure! Thanks bud, we did it!

**Comment by Kataiser** [comment]
Yay
