### ISSUE TITLE
crash when launching the exe

### ISSUE THREAD

**Issue by MilkMGN** [Kataiser/tf2-rich-presence#90]
whenever i launch any of the exe files, it doesn't work. the error is 

> Traceback (most recent call last):
>  File "F:\TF2 Rich Presence v1.13.1\\resources\launcher.py", line 67, in launch
>    loaded_module.launch()
>  File "main.py", line 102, in main.launch
>  File "main.py", line 90, in main.launch
>  File "settings.py", line 421, in settings.compare_settings
> KeyError: 'trim_console_log'

i think this might be caused by my game directory being under a different drive to steam?

**Comment by Kataiser** [comment]
I've (probably) fixed this as of 6e7c5bf. It shouldn't care where Steam and TF2 are installed, but is more likely caused using an older version of this program (< v1.12) and then updating to v1.13, which is a bug in and of itself I need to fix. Anyway here's a build that should work for you: [tf2_rich_presence_v1.13.1.zip](https://github.com/Kataiser/tf2-rich-presence/files/4435403/tf2_rich_presence_v1.13.1.zip)

**Comment by Kataiser** [comment]
Did it work?

**Comment by MilkMGN** [comment]
sorry, i completely forgot that i commented this. testing now.

**Comment by MilkMGN** [comment]
nope, successfully launches tf but it has the same error of 
` TF2 Rich Presence (v1.13.1) by Kataiser
https://github.com/Kataiser/tf2-rich-presence

Launching Team Fortress 2 with Rich Presence enabled...


Traceback (most recent call last):
  File "C:\Users\spenc\Downloads\tf2_rich_presence_v1.13.1\TF2 Rich Presence v1.13.1\\resources\launcher.py", line 67, in launch
    loaded_module.launch()
  File "main.py", line 102, in main.launch
  File "main.py", line 90, in main.launch
  File "settings.py", line 425, in settings.compare_settings
KeyError: 'trim_console_log'

TF2 Rich Presence v1.13.1 has crashed, and the error has been reported to the developer.
(Consider opening an issue at https://github.com/Kataiser/tf2-rich-presence/issues)
Restarting` in 5 seconds... `

**Comment by Kataiser** [comment]
Alright here's another. This one should actively try to fix broken settings. 
[tf2_rich_presence_v1.13.1.zip](https://github.com/Kataiser/tf2-rich-presence/files/4448896/tf2_rich_presence_v1.13.1.zip)

**Comment by MilkMGN** [comment]
that seems to have worked, but ill see if it lasts a match

**Comment by Kataiser** [comment]
I'm gonna assume that it continued to work. If you get the same crash again, just reopen the issue. Thanks for the reports!
