### ISSUE TITLE
Error al iniciar

### ISSUE THREAD

**Issue by LechuMini** [Kataiser/tf2-rich-presence#91]
Cuando abro Launch TF2 with Rich Presence me da un error
![Error](https://user-images.githubusercontent.com/63259132/78915754-677b4a80-7a5a-11ea-957f-a12b561c04be.png)

**Comment by Kataiser** [comment]
Puedes instalar vc_redist.x86.exe desde [aquí](https://www.microsoft.com/en-us/download/details.aspx?id=48145). La mayoría de los juegos de Steam deberían haber hecho eso por ti así que no sé cómo sucedió. También, por favor usa el inglés en un repo Github inglés.

**Comment by LechuMini** [comment]
Oh, thank you very much, now it works!  😉

**Comment by Kataiser** [comment]
No problem, thanks for the report. I didn't know that was an issue before but I've added it to the readme.
