### ISSUE TITLE
translation failure in the Spanish language

### ISSUE THREAD

**Issue by LechuMini** [Kataiser/tf2-rich-presence#93]
Hello, I would like to report a translation failure in the Spanish language. To begin with, the TF2 icon says "Equipo Fortaleza 2" in Spanish, we do not say it directly, we called it in English originally. And also in the classes, we don't call the classes in their Spanish translation, we originally called it as it is in English, well that's it, the rest is well translated ...

![image](https://user-images.githubusercontent.com/63259132/79625301-2e944300-80f6-11ea-95fd-455ba07a30cf.png)

![image](https://user-images.githubusercontent.com/63259132/79625344-9185da00-80f6-11ea-988c-19c292e9fad4.png)

**Comment by Kataiser** [comment]
No se mucho español, asi que gracias por... the help lol, that's as far as I could get without a translation service. My like 6 years of high school + college Spanish are failing me. Would you mind taking a look at the settings window to see if everything looks good there as well? I'll fix the proper nouns at some point.

**Comment by Kataiser** [comment]
Here you are: 911b7ce 
Also, you're welcome to open pull requests if you'd like to directly contribute :)

**Comment by LechuMini** [comment]
Oh sorry, the truth when I put Google Chrome and translate it automatically it sounded weird XD, instead of saying "Solicitud de Extracción" I should say Suggestions or something like that, sorry again

**Comment by LechuMini** [comment]
I am happy to help you with the Spanish translations
